# Generated by Django 6.0 on 2025-12-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_techfest_participants_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('phone', models.CharField()),
                ('mode', models.CharField()),
                ('group', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('cgpa', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='techfest_participants',
        ),
    ]
