# Generated by Django 6.0 on 2025-12-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_admin_person_students_delete_techfest_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_person',
        ),
    ]
