# Generated by Django 6.0 on 2025-12-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_admin_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='cgpa',
            field=models.CharField(),
        ),
    ]
